### ISSUE TITLE
Please share the roadmap of this project

### ISSUE THREAD

**Issue by pattzaks** [ibm-security-innovation/libsecurity-go#2]
Hello,
This is a great and extremely useful project. Could you please let everyone know what are the future goals out of this project, the status or the roadmap ?
Thanks. Keep the good work going on.

**Comment by shmul** [comment]
Hi,

Thanks for the pat on the back. It is certainly great to hear you find this project useful. Can you share the use case you are integrating libsecurity with?
Our current target is to get feedback from users (i.e. developers working with the code) and to make the code more mature. The immediate candidate as the next feature would be support for logging, auditing and introspection but we haven't yet setup a timeline for this.
We consider the current release to be of beta quality. Once sufficient feedback is gathered from users (and there are a couple of projects using it currently) we'll consider an official 1.0 release.

Cheers,
Shmul
